<?php
$z[0]=Array("flink","  [field:link /]  &nbsp;&nbsp;",114,204);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",476,497);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",591,612);
$z[2][4]['name']="cfg_dh";
$z[3]=Array("global"," </p>\r\n      <p>公司地址：{dede:global.cfg_dz",660,732);
$z[3][4]['name']="cfg_yx";
$z[4]=Array("sql"," \r\n        \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        \r\n        ",747,920);
$z[4][4]['sql']="Select content from dede_arctype where id=1";
$z[5]=Array("global","",1324,1348);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1433,1459);
$z[6][4]['name']="cfg_powerby";

?>