<?php
$z[0]=Array("global","",255,276);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("global","",370,391);
$z[1][4]['name']="cfg_dh";
$z[2]=Array("global"," </p>\r\n      <p>公司地址：{dede:global.cfg_dz",439,511);
$z[2][4]['name']="cfg_yx";
$z[3]=Array("sql"," \r\n        \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        \r\n        ",526,699);
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("global","",1103,1127);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",1212,1238);
$z[5][4]['name']="cfg_powerby";

?>